import Head from "next/head";
import Loading from "./Loading";
import Navbar from "./Navbar";
import { useSession } from "next-auth/react";

export default function Layout({ children }) {
	// current session
	const { data: session, status } = useSession();

	return (
		<div>
			<Head>
				<title>Chatter</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="font bg-main-white text-main-black min-h-screen overflow-x-hidden">
				{/* auth loading  */}
				{status === "loading" && <Loading />}

				{/* if auth is not loading */}
				{status !== "loading" && (
					<>
						<Navbar />
						{children}
					</>
				)}
			</main>
		</div>
	);
}
